<a href="https://colab.research.google.com/github/dukyoon13/Python/blob/main/api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

9920996b

In [ ]:
import requests # HTTP 요청을 보내기 위한 requests 라이브러리
import pandas as pd
import pprint

In [ ]:
url = "https://www.omdbapi.com/"
params = { # API 요청에 필요한 파라미터들을 딕셔너리로 정의
    "apikey": "9920996b" ,
    "t": "Avengers",
    "type": "movie",
    "y": "2012"
}
# GET 요청
response = requests.get(url, params=params)
print(response.status_code) # HTTP 응답 상태 코드(예: 200은 성공)를 출력

In [ ]:
# JSON 응답을 파이썬 객체로 변환
data = response.json() # 응답 본문을 JSON 형식으로 파싱하여 파이썬 딕셔너리로 변환
pprint.pprint(data)

{'Actors': 'Robert Downey Jr., Chris Evans, Scarlett Johansson',
 'Awards': 'Nominated for 1 Oscar. 40 wins & 81 nominations total',
 'BoxOffice': '$623,357,910',
 'Country': 'United States',
 'DVD': 'N/A',
 'Director': 'Joss Whedon',
 'Genre': 'Action, Sci-Fi',
 'Language': 'English, Russian',
 'Metascore': '69',
 'Plot': "Earth's mightiest heroes must come together and learn to fight as a "
         'team if they are going to stop the mischievous Loki and his alien '
         'army from enslaving humanity.',
 'Poster': 'https://m.media-amazon.com/images/M/MV5BNGE0YTVjNzUtNzJjOS00NGNlLTgxMzctZTY4YTE1Y2Y1ZTU4XkEyXkFqcGc@._V1_SX300.jpg',
 'Production': 'N/A',
 'Rated': 'PG-13',
 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.0/10'},
             {'Source': 'Rotten Tomatoes', 'Value': '91%'},
             {'Source': 'Metacritic', 'Value': '69/100'}],
 'Released': '04 May 2012',
 'Response': 'True',
 'Runtime': '143 min',
 'Title': 'The Avengers',
 'Type': 'movie',
 'Website': 'N/A',
 'Writer': 'Joss Whedon, Zak Penn',
 'Year': '2012',
 'imdbID': 'tt0848228',
 'imdbRating': '8.0',
 'imdbVotes': '1,547,278'}

In [ ]:
import requests

url = "https://www.omdbapi.com/"
params = {
    "apikey": "9920996b",
    "s": "Avengers" ,  # t 대신에 s는 Avengers에 해당 하는 모든 걸 찾기.
    "type": "movie"
}

response = requests.get(url, params=params)
data = response.json()
data

{'Search': [{'Title': 'The Avengers',
   'Year': '2012',
   'imdbID': 'tt0848228',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BNGE0YTVjNzUtNzJjOS00NGNlLTgxMzctZTY4YTE1Y2Y1ZTU4XkEyXkFqcGc@._V1_SX300.jpg'},
  {'Title': 'Avengers: Endgame',
   'Year': '2019',
   'imdbID': 'tt4154796',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg'},
  {'Title': 'Avengers: Infinity War',
   'Year': '2018',
   'imdbID': 'tt4154756',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg'},
  {'Title': 'Avengers: Age of Ultron',
   'Year': '2015',
   'imdbID': 'tt2395427',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BODBhYTg1NGQtNGVmNS00ZTdiLThjYTYtZDFkNzRiNTZmNDZjXkEyXkFqcGc@._V1_SX300.jpg'},
  {'Title': 'The Avengers',
   'Year': '1998',
   'imdbID': 'tt0118661',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BZTA4ZmZlZWQtZDRlYS00ZWZhLTk0MzEtYjExMGIzMTBlZDNlXkEyXkFqcGc@._V1_SX300.jpg'},
  {'Title': 'Ultimate Avengers: The Movie',
   'Year': '2006',
   'imdbID': 'tt0491703',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMTYyMjk0NTMwMl5BMl5BanBnXkFtZTgwNzY0NjAwNzE@._V1_SX300.jpg'},
  {'Title': 'Ultimate Avengers II',
   'Year': '2006',
   'imdbID': 'tt0803093',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BZjI3MTI5ZTYtZmNmNy00OGZmLTlhNWMtNjZiYmYzNDhlOGRkL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg'},
  {'Title': 'Next Avengers: Heroes of Tomorrow',
   'Year': '2008',
   'imdbID': 'tt1259998',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMTQ3NjExNjY4N15BMl5BanBnXkFtZTcwNTczODkwNQ@@._V1_SX300.jpg'},
  {'Title': 'Avengers Confidential: Black Widow & Punisher',
   'Year': '2014',
   'imdbID': 'tt3482378',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMTU2MDg0Njk4MF5BMl5BanBnXkFtZTgwMTY0OTIyMTE@._V1_SX300.jpg'},
  {'Title': 'Crippled Avengers',
   'Year': '1978',
   'imdbID': 'tt0077292',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BYjU2ODU5NzMtMzQ2NC00MmI5LWI1NjMtNmRmMjMzOTMxNWZhXkEyXkFqcGc@._V1_SX300.jpg'}],
 'totalResults': '134',
 'Response': 'True'}

In [ ]:
# 검색 결과 리스트 출력
movies = data["Search"]
for movie in movies:
  print(movie["Title"], movie['Year'])

The Avengers 2012
Avengers: Endgame 2019
Avengers: Infinity War 2018
Avengers: Age of Ultron 2015
The Avengers 1998
Ultimate Avengers: The Movie 2006
Ultimate Avengers II 2006
Next Avengers: Heroes of Tomorrow 2008
Avengers Confidential: Black Widow & Punisher 2014
Crippled Avengers 1978

In [ ]:
import pandas as pd

if 'Search' in data:
  m_df = pd.DataFrame(data['Search'])
else:
  m_df = pd.DataFrame([data]) # 'Search' 키가 없으면, data 자체가 단일 객체이므로 리스트로 감싸서 DataFrame으로 생성

display(m_df.head())

,Title,Year,imdbID,Type,Poster
0,The Avengers,2012,tt0848228,movie,https://m.media-amazon.com/images/M/MV5BNGE0YT...
1,Avengers: Endgame,2019,tt4154796,movie,https://m.media-amazon.com/images/M/MV5BMTc5MD...
2,Avengers: Infinity War,2018,tt4154756,movie,https://m.media-amazon.com/images/M/MV5BMjMxNj...
3,Avengers: Age of Ultron,2015,tt2395427,movie,https://m.media-amazon.com/images/M/MV5BODBhYT...
4,The Avengers,1998,tt0118661,movie,https://m.media-amazon.com/images/M/MV5BZTA4Zm...

In [ ]:
m_df = m_df.iloc[0:4] # 인덱스 0부터 3까지의 행만 선택
display(m_df)

,Title,Year,imdbID,Type,Poster
0,The Avengers,2012,tt0848228,movie,https://m.media-amazon.com/images/M/MV5BNGE0YT...
1,Avengers: Endgame,2019,tt4154796,movie,https://m.media-amazon.com/images/M/MV5BMTc5MD...
2,Avengers: Infinity War,2018,tt4154756,movie,https://m.media-amazon.com/images/M/MV5BMjMxNj...
3,Avengers: Age of Ultron,2015,tt2395427,movie,https://m.media-amazon.com/images/M/MV5BODBhYT...

In [ ]:
# 어벤져스 시리즈 4편 정보 수집

# m_df의 'Title'과 'Year' 컬럼 값으로 titles 리스트를 생성
titles = [(row['Title'], row['Year']) for index, row in m_df.iterrows()]
print(titles)
# 각 영화 정보를 저장할 빈 리스트
movies = []


url = "https://www.omdbapi.com/"
for title, year in titles:
  params = {
      "apikey": "9920996b" ,
      "t": title ,
      "type": "movie",
      "y": year
  }
  response = requests.get(url, params=params) # RESTful api
  data = response.json()
  movies.append({
      "title": data.get('Title'),  # RESTful api 에서 웹서버에 데이터 요청 get 방식
      "year": data.get("Year"),
      "director": data.get('Director'),
      "imdbRating": data.get('imdbRating'),
      "genre": data.get('Genre')
  })

  pprint.pprint(movies)
  df = pd.DataFrame(movies)

  # 데이터프레임으로 변환
  df = pd.DataFrame(movies)
  display(df)

[('The Avengers', '2012'), ('Avengers: Endgame', '2019'), ('Avengers: Infinity War', '2018'), ('Avengers: Age of Ultron', '2015')]
[{'director': 'Joss Whedon',
  'genre': 'Action, Sci-Fi',
  'imdbRating': '8.0',
  'title': 'The Avengers',
  'year': '2012'}]

          title  year     director imdbRating           genre
0  The Avengers  2012  Joss Whedon        8.0  Action, Sci-Fi

[{'director': 'Joss Whedon',
  'genre': 'Action, Sci-Fi',
  'imdbRating': '8.0',
  'title': 'The Avengers',
  'year': '2012'},
 {'director': 'Anthony Russo, Joe Russo',
  'genre': 'Action, Adventure, Sci-Fi',
  'imdbRating': '8.4',
  'title': 'Avengers: Endgame',
  'year': '2019'}]

,title,year,director,imdbRating,genre
0,The Avengers,2012,Joss Whedon,8.0,"Action, Sci-Fi"
1,Avengers: Endgame,2019,"Anthony Russo, Joe Russo",8.4,"Action, Adventure, Sci-Fi"

[{'director': 'Joss Whedon',
  'genre': 'Action, Sci-Fi',
  'imdbRating': '8.0',
  'title': 'The Avengers',
  'year': '2012'},
 {'director': 'Anthony Russo, Joe Russo',
  'genre': 'Action, Adventure, Sci-Fi',
  'imdbRating': '8.4',
  'title': 'Avengers: Endgame',
  'year': '2019'},
 {'director': 'Anthony Russo, Joe Russo',
  'genre': 'Action, Adventure, Sci-Fi',
  'imdbRating': '8.4',
  'title': 'Avengers: Infinity War',
  'year': '2018'}]

,title,year,director,imdbRating,genre
0,The Avengers,2012,Joss Whedon,8.0,"Action, Sci-Fi"
1,Avengers: Endgame,2019,"Anthony Russo, Joe Russo",8.4,"Action, Adventure, Sci-Fi"
2,Avengers: Infinity War,2018,"Anthony Russo, Joe Russo",8.4,"Action, Adventure, Sci-Fi"

[{'director': 'Joss Whedon',
  'genre': 'Action, Sci-Fi',
  'imdbRating': '8.0',
  'title': 'The Avengers',
  'year': '2012'},
 {'director': 'Anthony Russo, Joe Russo',
  'genre': 'Action, Adventure, Sci-Fi',
  'imdbRating': '8.4',
  'title': 'Avengers: Endgame',
  'year': '2019'},
 {'director': 'Anthony Russo, Joe Russo',
  'genre': 'Action, Adventure, Sci-Fi',
  'imdbRating': '8.4',
  'title': 'Avengers: Infinity War',
  'year': '2018'},
 {'director': 'Joss Whedon',
  'genre': 'Action, Adventure, Sci-Fi',
  'imdbRating': '7.3',
  'title': 'Avengers: Age of Ultron',
  'year': '2015'}]

,title,year,director,imdbRating,genre
0,The Avengers,2012,Joss Whedon,8.0,"Action, Sci-Fi"
1,Avengers: Endgame,2019,"Anthony Russo, Joe Russo",8.4,"Action, Adventure, Sci-Fi"
2,Avengers: Infinity War,2018,"Anthony Russo, Joe Russo",8.4,"Action, Adventure, Sci-Fi"
3,Avengers: Age of Ultron,2015,Joss Whedon,7.3,"Action, Adventure, Sci-Fi"

In [ ]:
df_sorted = df.sort_values(by='imdbRating', ascending=False)
display(df_sorted)

,title,year,director,imdbRating,genre
1,Avengers: Endgame,2019,"Anthony Russo, Joe Russo",8.4,"Action, Adventure, Sci-Fi"
2,Avengers: Infinity War,2018,"Anthony Russo, Joe Russo",8.4,"Action, Adventure, Sci-Fi"
0,The Avengers,2012,Joss Whedon,8.0,"Action, Sci-Fi"
3,Avengers: Age of Ultron,2015,Joss Whedon,7.3,"Action, Adventure, Sci-Fi"

In [ ]:
import requests
# 삼성전자 종목 코드
# https://finance.naver.com/item/main.naver?code=005930

# sk하이닉스 종목 코드 000660
# https://finance.naver.com/item/main.naver?code=000660

In [ ]:
code = "005930"
url = "http://finance.naver.com/itemmain.naver?code={}"

response = requests.get(url, format(code))
print(response.text) # 응답 HTML 출력

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=euc-kr">
<title>네이버 :: 세상의 모든 지식, 네이버</title>

<style type="text/css">
.error_content * {margin:0;padding:0;}
.error_content img{border:none;}
.error_content em {font-style:normal;}
.error_content {width:410px; margin:80px auto 0; padding:57px 0 0 0; font-size:12px; font-family:"나눔고딕", "NanumGothic", "돋움", Dotum, AppleGothic, Sans-serif; text-align:left; line-height:14px; background:url(https://ssl.pstatic.net/static/common/error/090610/bg_thumb.gif) no-repeat center top; white-space:nowrap;}
.error_content p{margin:0;}
.error_content .error_desc {margin-bottom:21px; overflow:hidden; text-align:center;}
.error_content .error_desc2 {margin-bottom:11px; padding-bottom:7px; color:#888; line-height:18px; border-bottom:1px solid #eee;}
.error_content .error_desc3 {clear:both; color:#888;}
.error_content .error_desc3 a {color:#004790; text-decoration:underline;}
.error_content .error_list_type {clear:both; float:left; width:410px; _width:428px; margin:0 0 18px 0; *margin:0 0 7px 0; padding-bottom:13px; font-size:13px; color:#000; line-height:18px; border-bottom:1px solid #eee;}
.error_content .error_list_type dt {float:left; width:60px; _width /**/:70px; padding-left:10px; background:url(https://ssl.pstatic.net/static/common/error/090610/bg_dot.gif) no-repeat 2px 8px;}
.error_content .error_list_type dd {float:left; width:336px; _width /**/:340px; padding:0 0 0 4px;}
.error_content .error_list_type dd span {color:#339900; letter-spacing:0;}
.error_content .error_list_type dd a{color:#339900;}
.error_content p.btn{margin:29px 0 100px; text-align:center;}
</style>
</head>
<!-- ERROR -->
<body>
<div class="error_content">
	<p class="error_desc"><img src="https://ssl.pstatic.net/static/common/error/090610/txt_desc5.gif" width="319" height="30" alt="페이지를 찾을 수 없습니다."></p>
	<p class="error_desc2">방문하시려는 페이지의 주소가 잘못 입력되었거나,<br>
		페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.<br>
		입력하신 주소가 정확한지 다시 한번 확인해 주시기 바랍니다.
	</p>
	<p class="error_desc3">관련 문의사항은 <a href="https://help.pay.naver.com" target="_blank">고객센터</a>에 알려주시면 친절히 안내해드리겠습니다. 감사합니다.</p>
	<p class="btn">
		<a href="javascript:history.back()"><img src="https://ssl.pstatic.net/static/common/error/090610/btn_prevpage.gif" width="115" height="35" alt="이전 페이지로"></a>
		<a href="https://finance.naver.com"><img src="https://ssl.pstatic.net/static/nfinance/btn_home.gif" width="115" height="35" alt="증권홈으로"></a>
	</p>
</div>
</body>
</html>